server:
  port: 9092

spring:
  application:
    name: eventsourcing-cqrs-jejuBank

  # DB connection
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/Jeju?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: jeju
    password: axon
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect # mysql 8.0 이후 접속 시 allowPublicKeyRetrieval=true DB 설정이 필요하다
    hibernate:
      ddl-auto: update
      format_sql: true
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false

# Axon Framework 설정
axon:
  serializer:
    general: xstream
  axonserver:
    servers: 127.0.0.1:8124

# logging
logging:
  level:
    com:
      cqrs:
        query: debug
    org:
      axonframework: debug

---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: prod