spring:
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/Axon?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: axon
    password: vntg
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      format_sql: true

